### ISSUE TITLE
Ability to Edit Active Experiments

### ISSUE THREAD

**Issue by combimatrixai-lab** [CombiMatrix-AI/CombiMatrix.Py#2]
![image](https://github.com/user-attachments/assets/c62bf131-bb08-4d28-bb7c-f350dc28f45d)

User needs to be able to edit experiments that are already defined in the list.

**Comment by lorenashfield** [comment]
Active experiments can be edited by highlighting the experiment and selecting alternate options on the left side dropdowns

**Comment by lorenashfield** [comment]
Also pull a more recent version
